---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 2048

platforms:
  - name: ubuntu-13.10
  - name: debian-7.4
  - name: centos-6.5
  - name: fedora-19
  
suites:
  - name: default
    run_list:
      - recipe[rethinkdb]
    attributes: {}
    excludes:
      - debian-7.4
      - fedora-19
  - name: package
    run_list:
      - recipe[rethinkdb::package]
    attributes: {}
    excludes:
      - debian-7.4
      - fedora-19
  - name: source
    run_list:
      - recipe[rethinkdb::source]
    attributes: {}
